apiVersion: v1
kind: Pod
metadata:
  name: tolerations
  labels:
    purpose: "tolerations-demo"
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "hardware"
    operator: "gpu"
    effect: "NoSchedule"
    tolerations:
  - key: "hardware"
    operator: "gpu"
    effect: "NoExecute"